[package]
type = 'lib'
lang = 'bash'
name = 'bats-all'
slug = 'bats_all'
version = '5.3.1'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'An aggregation of the three most popular Bats libraries'
