[package]
name = 'bats-alls'
slug = 'bats-alls'
version = '3.0.1'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = []
sourceDirs = []
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
