[package]
name = 'bats-all'
slug = 'bats_all'
version = '4.2.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = []
sourceDirs = []
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
