[package]
name = 'bats-common-utils'
slug = 'bats-common-utils'
version = ''
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = []
sourceDirs = ['bats-assert-src', 'bats-file-src', 'bats-support-src']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
